import * as approvedListsService from "../service/ApprovedListsService";
import {ApprovedListType, IApprovedListItemWrite} from "../objects/ApprovedLists";
import * as userService from "../../../api/users/services/userService";
import {IUserLoggedIn} from "../../services/services/users/contracts/IUser";

export async function seed() {
    const existing = await approvedListsService.read({type: ApprovedListType.OWNER, searchableOnly: false, limit: 1});

    if (!existing || !existing.length) {
        console.log("Seeding owners");

        const toAdd: IApprovedListItemWrite[] = owners.map((m) => {
            return {
                value: m,
                type: ApprovedListType.OWNER,
                searchable: true,
            } as IApprovedListItemWrite;
        });

        const systemUser: IUserLoggedIn = await userService.getSystemUserAsync();
        for (let i = 0; i < toAdd.length; i++) {
            try {
                await approvedListsService.create(systemUser, {ip: "127.0.0.1", user_agent: "server"}, toAdd[i]);
            } catch (err) {
                console.error(err);
            }
        }
    }
}

const owners: string[] = [
    "1st Lake Properties",
    "29th Street Capital",
    "360 Residential",
    "4G Ventures",
    "A&E Real Estate Holdings",
    "A.R. Building",
    "AAA Management ",
    "Abacus Capital Group",
    "Acacia Capital",
    "AEW Capital Management",
    "AHC",
    "AIG Global Real Estate",
    "AION Partners",
    "Alliance Bernstein",
    "AMCAL Multi-Housing",
    "American Realty Advisors (ARA)",
    "Antheus Capital",
    "Anthony Saris",
    "Apartment Services",
    "ApexOne",
    "APM Management",
    "Aragon Holdings",
    "Arbor Realty Trust",
    "Ares Management",
    "Arnel & Affiliates",
    "ASB Real Estate Investments",
    "Asia Capital Real Estate",
    "Aspen Heights Partners",
    "Atlantic Housing Partners",
    "Aukum",
    "Avanath Capital Management",
    "Avila Real Estate",
    "AVR Realty",
    "B & M Management",
    "Bainbridge Companies",
    "Banner Property Management",
    "Banyan Realty Management",
    "Barings",
    "Barings Real Estate Advisers",
    "BASCOM",
    "Bascom Group",
    "BC Property Investments",
    "Beacon Communities",
    "Belkorp Industries, Inc.",
    "Benedict Canyon Equities",
    "Berkshire Property Advisors",
    "Beztak Companies",
    "BH Equities",
    "Bigos Management",
    "BlackRock",
    "Blackstone Group",
    "Blake | Griggs Properties",
    "Blue Marble Development",
    "Blue Ridge Companies",
    "Blue Roc Premier Properties",
    "Bluerock Real Estate",
    "Bonaventure Realty Group",
    "Boston Capital Group",
    "Boston Housing Authority",
    "Braddock & Logan",
    "Breeden Company, The",
    "BRG Apartments",
    "BRIDGE Housing",
    "Bridge Investment Group Partners",
    "Broadmoor",
    "Brodsky Organization, The",
    "Brookfield Properties",
    "Brown Gibbons Lang & Company",
    "BSR Trust",
    "Buckingham Companies",
    "Build Inc.",
    "Burden Inc.",
    "Burton Carol Management",
    "Calida Group",
    "Cammeby's International",
    "Capital Real Estate",
    "Capital Realty Group",
    "CAPREIT",
    "Capstone Companies",
    "Carabetta Companies",
    "Carlisle Development Group",
    "Carmel Partners",
    "Carroll Companies, The",
    "Carter-Haston Real Estate Services",
    "Cascade Affordable",
    "Caspian Properties, Inc",
    "Castle Creek Homes",
    "Castle Lantera",
    "Castlewood Development",
    "Casto",
    "CBRE Global Investors",
    "Centennial Holding Company",
    "Chartwell",
    "Chestnut Hill Realty",
    "Chetrit Group, The",
    "Chicago Housing Authority",
    "Churchill Forge Properties",
    "C-III Asset Management",
    "Clarion Partners",
    "ClearSky Capital",
    "Clipper Equity",
    "Collier Companies",
    "ColRich Group",
    "Columbia Residential",
    "Columbus Realty Partners",
    "Commerce Capital Partners",
    "Commercial Investment Properties",
    "Community Builders, The",
    "Compass Development Group",
    "Conifer Realty",
    "Consulting Associates",
    "Continental Realty",
    "Corcoran Jennison Companies",
    "Covenant Capital Group",
    "Covey Regional Management",
    "Crescent Communities",
    "Cross Equities",
    "Crow Holdings",
    "Crowne Partners",
    "Cuyahoga Metropolitan Housing Authority",
    "DAI Utah",
    "Dallas Housing Authority",
    "DC Housing Authority",
    "Deancurt Realty Group",
    "Decron Properties",
    "Derk Pardoe",
    "Deutsche Bank Asset Management",
    "Devco",
    "Dinerstein Companies",
    "Dittmar Company",
    "Douglas Development",
    "DRA Advisors",
    "Draper & Kramer",
    "Drucker & Falk",
    "DSG Group",
    "DTN Management",
    "Dwayne Henson Investments",
    "Dweck Properties",
    "E & M Associates",
    "E & S Ring Management",
    "Eagle Rock Advisors",
    "EAH",
    "Eaton Vance",
    "ECI Group",
    "Eden Housing",
    "EdR",
    "Edwards Companies",
    "Eighteen Capital Group",
    "El Ad National Properties",
    "El Paso Housing Authority",
    "Elmington Capital Group",
    "ELRH Investments",
    "Embassy Group, The",
    "Endeavor Real Estate Group",
    "Ensign Group",
    "EPT Land Communities",
    "Equus Capital Partners",
    "Ergas Group, The",
    "ESG Kullen",
    "Eureka Holdings",
    "Everest Holdings",
    "Fairfield Residential",
    "Falls Apartment Group",
    "Fath Properties",
    "Fiduciary Real Estate Development",
    "Fieldstone Properties",
    "Fifield Companies",
    "First Pacific Group",
    "Flagship Homes",
    "Flaherty & Collins Properties",
    "Fogelman Properties",
    "Fore Property Company",
    "Forge Partners",
    "Fortbay",
    "Forum Real Estate Group",
    "Foulger-Pratt",
    "Foundation of CSUMB",
    "Fowler Property Acquisitions",
    "Francis Property Management",
    "Freeman Webb",
    "Friedkin Realty Group",
    "FrontRange Capital Partners",
    "FSC Realty",
    "G W Williams Co.",
    "GAIA Real Estate",
    "Gaines Investment Trust",
    "Galman Group, The",
    "Gardiner Properties, LLC",
    "Gatesco",
    "Gelt",
    "GEM Management",
    "Gene B. Glick Company",
    "General Services Corporation",
    "Gerson Bakar & Associates",
    "GH Palmer Associates",
    "Glenwood Management",
    "Global Ministries Foundation",
    "Goff Capital Partners",
    "Goldberg Companies",
    "Goldelm",
    "Goodman Real Estate",
    "Grand Peaks Properties",
    "Greenheart Land Company",
    "Greystone",
    "Greystone Group",
    "Griffis Residential",
    "Gross Builders",
    "Grubb Properties",
    "GSL Properties",
    "Gupta, Ajay K.",
    "GWR Equities",
    "Haley Real Estate",
    "Hamilton Partners, LP",
    "Hamilton Point Investments",
    "Hampshire Properties",
    "Hanover Company, The",
    "Harrison Street",
    "Hartman & Tyner",
    "Harvest Equities",
    "Harvest Investments",
    "Hawkeye Partners",
    "Hayman Company",
    "Heatherwood Communities",
    "Heitman",
    "Hendersen-Webb",
    "Hensyn",
    "Hercules Real Estate Services",
    "Heritage Properties",
    "HFF",
    "HHHunt",
    "Highridge Costa Companies",
    "Hills Communities",
    "Hines Interests",
    "Horizon Realty Advisors",
    "Housing Authority of Baltimore City",
    "Housing Trust Group",
    "Houston Housing Authority",
    "Hubbell Realty",
    "Hunt Companies",
    "Ilan Investments",
    "Integral Group",
    "InterCapital Partners",
    "Interurban Corporation",
    "Invesco Real Estate",
    "Investcorp",
    "Investment Concepts",
    "Investors Capital Group",
    "Ironstate Development",
    "J. Milton & Associates",
    "Jamison Properties",
    "JCM Partners",
    "JF Capital",
    "JLB Partners",
    "John M. Corcoran and Company",
    "Johnson Development Associates (JDA)",
    "Jonathan Rose Companies",
    "JP Morgan Asset Management",
    "JPI Partners, LLC",
    "JRK Property Holdings",
    "Juniper Investment Group",
    "Junius Real Estate Partners",
    "JVM Realty",
    "K&D",
    "K2 ",
    "Kamson Corporation, The",
    "KC Venture Group",
    "KDF Communities",
    "Keller Investments",
    "Kettler",
    "King County Housing Authority",
    "Klein Financial Corporation",
    "Klingbeil Capital Management",
    "Kushner Companies",
    "L+M Development Partners",
    "Land & Company",
    "Landmark Companies",
    "LaSalle Investment Management",
    "LDG Development",
    "Legacy Partners",
    "Lifestyle Communities",
    "Lindy Property Management",
    "Lone Star Funds",
    "Los Angeles Housing Authority",
    "Lowe Enterprises",
    "Lowe Property Group",
    "Lyon Capital Ventures",
    "Mack-Cali Realty",
    "Madera Companies",
    "Magellan Development Group",
    "Magna Management Investors",
    "Mahaffey Apartment Group",
    "Mandel Group",
    "Marquette Companies",
    "Maryland Management",
    "MBK Homes",
    "McCormack Baron Salazar",
    "McMillin Development Company",
    "Meagher Jr., Donald T.",
    "Melia Homes",
    "Menlo Capital Group",
    "Mercy Housing",
    "Mesirow Financial",
    "MetLife Real Estate Investment",
    "Metropolitan Development & Housing Agency",
    "Michaels Development",
    "Michelson Organization",
    "Mid-City Financial",
    "MidPen Housing",
    "Midwest Diversified Properties",
    "MIG Real Estate",
    "Millburn & Company",
    "Miller-Valentine Group",
    "Mills Properties",
    "Modus Development",
    "Momentum Real Estate Partners",
    "Monogram Residential Trust",
    "Monument Real Estate Services",
    "Morgan Group",
    "Morguard North American Residential",
    "MRP Realty",
    "National Church Residences",
    "National Community Renaissance",
    "National Property Management Associates",
    "Nautilus Group",
    "New Life Multifamily Management",
    "New York City Housing Authority",
    "Newport Venture Capital",
    "NextGen Apartments",
    "NHP Foundation",
    "NMS Property Services",
    "North American Properties",
    "Northwestern Mutual",
    "Northwood Ravin",
    "NRP Group",
    "NTS",
    "NY Life Insurance Company",
    "Oakwood Development",
    "Olympic Residential Group",
    "O'Neill Properties Group",
    "Onni Group",
    "Oregon Pacific Investments",
    "Ovation Development",
    "Pacific Life Insurance Company",
    "Pacific Urban Residential",
    "Pacifica Companies",
    "Paradigm Development",
    "Parkmeed Properties",
    "Pathfinder Partners, LLC",
    "Peak Capital Partners",
    "Pennrose Properties",
    "Pensam Capital",
    "Peterson Companies, The",
    "PGIM Real Estate",
    "Phillips Management Group",
    "Pinnacle Housing Group",
    "PMC Property Group",
    "Pollack Shores",
    "Post Investment Group",
    "Praedium Group",
    "Preservation of Affordable Housing",
    "PRG Real Estate",
    "Price Development Group",
    "Price Realty",
    "Prime Group",
    "Progress Management",
    "Providence Management Company",
    "Provident Realty Advisors",
    "Prudential (PGIM)",
    "Pure Multi",
    "Quest Management Group",
    "QVT Mount Auburn Capital",
    "RADCO Companies",
    "Raintree Partners",
    "RCMI",
    "Read Property Group",
    "Real Capital Solutions",
    "RedHill Realty Investors, LP",
    "Redwood Capital Group",
    "Redwood Living",
    "Regional Management",
    "Reliant Group",
    "Reliant Group, The",
    "Retirement Housing Foundation",
    "Ritchie Group",
    "Rivendell Global Real Estate Inc.",
    "Rockpoint Group",
    "Rockrose Development",
    "Rockwell Management",
    "Rockwood Capital",
    "RXR Realty",
    "Ryan Companies",
    "S.L. Nusbaum Realty",
    "S2 Residential",
    "Salmon Electric",
    "San Antonio Housing Authority",
    "Sand Hill Property Company",
    "Schorr, Shraga F.",
    "Scully Company",
    "Sealy Management",
    "Seattle Housing Authority",
    "Security National Financial",
    "Security Properties",
    "Seldin Company",
    "Shamrock Communities",
    "Shapell Investments",
    "Sherman Associates",
    "Silver Street Development",
    "Snider Executive Offices",
    "The Sobrato Organization (TSO)",
    "Somerset Partners",
    "Southport Financial Services",
    "St. Anton Partners",
    "St. Regis Properties",
    "Standard Management Company",
    "Starwood Capital Group",
    "State Teachers Retirement System of Ohio",
    "Stellar Management",
    "Sterling Group",
    "Sterling University Housing",
    "Stockbridge",
    "Strata Equity",
    "Strategic Capital Partners",
    "Strategic Realty Capital",
    "Studio Management Services, Inc.",
    "Summerhill Apartment Communities",
    "TA Associates Realty",
    "TAK Group",
    "Tarigo Company",
    "Texas Capital Partners",
    "TF Cornerstone",
    "TGM Associates",
    "Thalhimer Realty Partners",
    "Threshold Capital",
    "TIAA",
    "Timbercreek",
    "Timberlane Partners",
    "Tincath",
    "Toll Brothers Apartment Living",
    "Tonti Properties",
    "Trammell Crow Residential (TCR)",
    "Transwestern Commercial Services",
    "Tri City Rentals",
    "Tribute Companies",
    "TriCal Construction",
    "Trinsic Residential Group",
    "TruAmerica Multifamily",
    "True Craft Residential",
    "Tungsten Properties, Inc.",
    "UBS Realty Investors",
    "Uinta Land Company",
    "Urschel Company",
    "USAA",
    "Van Trust ",
    "Veritas Investment",
    "Vesta Corporation",
    "Vestcor Companies",
    "Volunteers of America",
    "Vornado Realty Trust",
    "W3",
    "Walton Communities",
    "Warren Properties",
    "Washington Real Estate Investment Trust",
    "Watermark Residential",
    "Waypoint Property Group",
    "Westdale Asset Management",
    "Western National Investments",
    "Westlake Urban, LLC",
    "Westland Real Estate Group",
    "White Eagle Property Group",
    "White Oak Partners",
    "William C. Smith & Company",
    "Wingate Companies",
    "WLA Investments",
    "Wolff Companies",
    "Woodfield Investments",
    "WRH Realty Services",
    "Wright Development Group",
    "Yolanda E Guerrero Trust",
    "ZOM",
];
