module.exports = {
    RAYGUN_APIKEY: process.env.RAYGUN_APIKEY || 'pVcxW+v/CU01JzU+42/WAg==',
    MONGODB_URI: process.env.MONGOHQ_URL || process.env.MONGOLAB_URI  || process.env.MONGODB_URI || 'mongodb://127.0.0.1:27017/Biradix',
    MONGODB_POOL_SIZE:100,
    SENDGRID_USERNAME : process.env.SENDGRID_USERNAME || 'app43915263@heroku.com',
    SENDGRID_PASSWORD : process.env.SENDGRID_PASSWORD || 'cypsntld9977',
    SENDGRID_API_KEY :  process.env.SENDGRID_API_KEY || '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',
    MODE : process.env.mode || 'production',
    PORT : process.env.PORT || 2000,
    SECRET : process.env.secret || 'test',
    API_PATH : process.env.apipath || '/api/1.0/',
    NEW_RELIC_LICENSE_KEY : process.env.NEW_RELIC_LICENSE_KEY || '71d799aa1dc64627ec44bbc97103b81fa1e68a7c',
    NEW_RELIC_NAME : process.env.NEW_RELIC_NAME || 'Localhost',
    REDIS_URL : process.env.REDIS_URL || 'redis://localhost:6379',
    EXCEL_URL : process.env.EXCEL_URL || 'http://localhost:12008/excel',
    CLOUDAMQP_URL : process.env.CLOUDAMQP_URL || 'amqp://localhost',
    DASHBOARD_QUEUE : "jobs.property.dashboard",
    PROFILE_QUEUE : "jobs.property.profile",
    PDF_PROFILE_QUEUE : "jobs.property.profile.pdf",
    PDF_REPORTING_QUEUE : "jobs.reporting.pdf",
    HISTORY_COMPARE_REPORT_QUEUE : "jobs.reporting.history_compare",
    NOTIFICATIONS_QUEUE : "jobs.notifications.property",
    WEB_STATUS_QUEUE : "jobs.status.web",
    PHANTOM_STATUS_QUEUE : "jobs.status.phantom",
    GUESTS_QUEUE : "jobs.propertyusers.guests",
    IMPORT_QUEUE : "jobs.temp.import",
    IMPORT_USERS_QUEUE : "jobs.temp.importUsers",
    RUN_PHANTOM : process.env.RUN_PHANTOM || "web",
    RUN_DASHBOARD : process.env.RUN_DASHBOARD || "web",
    HEROKU_API_KEY : process.env.HEROKU_API_KEY,
    HEROKU_APP : process.env.HEROKU_APP || "birdaixplatform-dev",
    PDF_HIT_COUNT: 0,
    PDF_HIT_RESTART: process.env.PDF_HIT_RESTART || 2,
    PDF_WORKERS: process.env.PDF_WORKERS || 3,
    SEED_DEMO : process.env.SEED_DEMO == "1" || true,
    PROJECT_DIR : __dirname
    //SKIPRABBIT : true

}